{"uuid":"a007e548-e730-4c5a-aac3-599f12878ab6","historyId":"8f03563ea964475080b425beaa0be48d","fullName":"com.dsalgo.qa.testcases.MainPageAndLoginTest.successfulLogin","labels":[{"name":"package","value":"com.dsalgo.qa.testcases.MainPageAndLoginTest"},{"name":"testClass","value":"com.dsalgo.qa.testcases.MainPageAndLoginTest"},{"name":"testMethod","value":"successfulLogin"},{"name":"parentSuite","value":"dsalgoProject"},{"name":"suite","value":"dsalgoRegression"},{"name":"subSuite","value":"com.dsalgo.qa.testcases.MainPageAndLoginTest"},{"name":"host","value":"DESKTOP-US9O7O0"},{"name":"thread","value":"20104@DESKTOP-US9O7O0.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Story Name: To check the successful login scenario"},{"name":"severity","value":"blocker"}],"links":[],"name":"successfulLogin","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [Numpy Ninja5] but found [Numpy Ninja]","trace":"java.lang.AssertionError: expected [Numpy Ninja5] but found [Numpy Ninja]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:136)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:575)\r\n\tat org.testng.Assert.assertEquals(Assert.java:585)\r\n\tat com.dsalgo.qa.testcases.MainPageAndLoginTest.successfulLogin(MainPageAndLoginTest.java:86)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)\r\n\tat org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:766)\r\n\tat org.testng.TestRunner.run(TestRunner.java:587)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1109)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1039)\r\n\tat org.testng.TestNG.run(TestNG.java:1007)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","description":"Test Case to verify the user is logged in successfully","steps":[{"name":"Get the Main Page title","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1652730857888,"stop":1652730857894}],"attachments":[],"parameters":[],"start":1652730857888,"stop":1652730857897}