<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-US9O7O0" failures="1" tests="5" name="com.dsalgo.qa.testcases.MainPageAndLoginTest" time="20.817" errors="0" timestamp="2022-05-16T12:55:03 PDT" skipped="2">
  <testcase classname="com.dsalgo.qa.testcases.MainPageAndLoginTest" name="verifyLogin" time="4.630"/>
  <system-out/>
  <testcase classname="com.dsalgo.qa.testcases.MainPageAndLoginTest" name="successfulLogin" time="3.279">
    <skipped/>
  </testcase> <!-- successfulLogin -->
  <system-out/>
  <testcase classname="com.dsalgo.qa.testcases.MainPageAndLoginTest" name="successfulLogin" time="4.929">
    <skipped/>
  </testcase> <!-- successfulLogin -->
  <system-out/>
  <testcase classname="com.dsalgo.qa.testcases.MainPageAndLoginTest" name="verifyLogin" time="4.756"/>
  <system-out/>
  <testcase classname="com.dsalgo.qa.testcases.MainPageAndLoginTest" name="successfulLogin" time="3.223">
    <failure message="expected [Numpy Ninja5] but found [Numpy Ninja]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Numpy Ninja5] but found [Numpy Ninja]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.dsalgo.qa.testcases.MainPageAndLoginTest.successfulLogin(MainPageAndLoginTest.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- successfulLogin -->
  <system-out/>
</testsuite> <!-- com.dsalgo.qa.testcases.MainPageAndLoginTest -->
